/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppTrashRouteImport } from './routes/_app/trash'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppNotesRouteImport } from './routes/_app/notes'
import { Route as AppImportAtaRouteImport } from './routes/_app/import-ata'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppTasksIndexRouteImport } from './routes/_app/tasks.index'
import { Route as AppTasksListRouteImport } from './routes/_app/tasks.list'
import { Route as AppTasksKanbanRouteImport } from './routes/_app/tasks.kanban'
import { Route as AppTasksCalendarRouteImport } from './routes/_app/tasks.calendar'
import { Route as AppClientReportClientIdRouteImport } from './routes/_app/client-report.$clientId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTrashRoute = AppTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppImportAtaRoute = AppImportAtaRouteImport.update({
  id: '/import-ata',
  path: '/import-ata',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppTasksListRoute = AppTasksListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppTasksKanbanRoute = AppTasksKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppTasksCalendarRoute = AppTasksCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppClientReportClientIdRoute = AppClientReportClientIdRouteImport.update({
  id: '/client-report/$clientId',
  path: '/client-report/$clientId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof AppClientsRoute
  '/dashboard': typeof AppDashboardRoute
  '/import-ata': typeof AppImportAtaRoute
  '/notes': typeof AppNotesRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRouteWithChildren
  '/trash': typeof AppTrashRoute
  '/users': typeof AppUsersRoute
  '/client-report/$clientId': typeof AppClientReportClientIdRoute
  '/tasks/calendar': typeof AppTasksCalendarRoute
  '/tasks/kanban': typeof AppTasksKanbanRoute
  '/tasks/list': typeof AppTasksListRoute
  '/tasks/': typeof AppTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof AppClientsRoute
  '/dashboard': typeof AppDashboardRoute
  '/import-ata': typeof AppImportAtaRoute
  '/notes': typeof AppNotesRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/trash': typeof AppTrashRoute
  '/users': typeof AppUsersRoute
  '/client-report/$clientId': typeof AppClientReportClientIdRoute
  '/tasks/calendar': typeof AppTasksCalendarRoute
  '/tasks/kanban': typeof AppTasksKanbanRoute
  '/tasks/list': typeof AppTasksListRoute
  '/tasks': typeof AppTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/import-ata': typeof AppImportAtaRoute
  '/_app/notes': typeof AppNotesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tasks': typeof AppTasksRouteWithChildren
  '/_app/trash': typeof AppTrashRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/client-report/$clientId': typeof AppClientReportClientIdRoute
  '/_app/tasks/calendar': typeof AppTasksCalendarRoute
  '/_app/tasks/kanban': typeof AppTasksKanbanRoute
  '/_app/tasks/list': typeof AppTasksListRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clients'
    | '/dashboard'
    | '/import-ata'
    | '/notes'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/trash'
    | '/users'
    | '/client-report/$clientId'
    | '/tasks/calendar'
    | '/tasks/kanban'
    | '/tasks/list'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clients'
    | '/dashboard'
    | '/import-ata'
    | '/notes'
    | '/reports'
    | '/settings'
    | '/trash'
    | '/users'
    | '/client-report/$clientId'
    | '/tasks/calendar'
    | '/tasks/kanban'
    | '/tasks/list'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/clients'
    | '/_app/dashboard'
    | '/_app/import-ata'
    | '/_app/notes'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/tasks'
    | '/_app/trash'
    | '/_app/users'
    | '/_app/client-report/$clientId'
    | '/_app/tasks/calendar'
    | '/_app/tasks/kanban'
    | '/_app/tasks/list'
    | '/_app/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trash': {
      id: '/_app/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AppTrashRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import-ata': {
      id: '/_app/import-ata'
      path: '/import-ata'
      fullPath: '/import-ata'
      preLoaderRoute: typeof AppImportAtaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/tasks/list': {
      id: '/_app/tasks/list'
      path: '/list'
      fullPath: '/tasks/list'
      preLoaderRoute: typeof AppTasksListRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/tasks/kanban': {
      id: '/_app/tasks/kanban'
      path: '/kanban'
      fullPath: '/tasks/kanban'
      preLoaderRoute: typeof AppTasksKanbanRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/tasks/calendar': {
      id: '/_app/tasks/calendar'
      path: '/calendar'
      fullPath: '/tasks/calendar'
      preLoaderRoute: typeof AppTasksCalendarRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/client-report/$clientId': {
      id: '/_app/client-report/$clientId'
      path: '/client-report/$clientId'
      fullPath: '/client-report/$clientId'
      preLoaderRoute: typeof AppClientReportClientIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppTasksRouteChildren {
  AppTasksCalendarRoute: typeof AppTasksCalendarRoute
  AppTasksKanbanRoute: typeof AppTasksKanbanRoute
  AppTasksListRoute: typeof AppTasksListRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
}

const AppTasksRouteChildren: AppTasksRouteChildren = {
  AppTasksCalendarRoute: AppTasksCalendarRoute,
  AppTasksKanbanRoute: AppTasksKanbanRoute,
  AppTasksListRoute: AppTasksListRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
}

const AppTasksRouteWithChildren = AppTasksRoute._addFileChildren(
  AppTasksRouteChildren,
)

interface AppRouteChildren {
  AppClientsRoute: typeof AppClientsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppImportAtaRoute: typeof AppImportAtaRoute
  AppNotesRoute: typeof AppNotesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRouteWithChildren
  AppTrashRoute: typeof AppTrashRoute
  AppUsersRoute: typeof AppUsersRoute
  AppClientReportClientIdRoute: typeof AppClientReportClientIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientsRoute: AppClientsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppImportAtaRoute: AppImportAtaRoute,
  AppNotesRoute: AppNotesRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRouteWithChildren,
  AppTrashRoute: AppTrashRoute,
  AppUsersRoute: AppUsersRoute,
  AppClientReportClientIdRoute: AppClientReportClientIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
