// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createFallbackQueryBuilder(message: string) {
  const error = new Error(message);

  const builder = new Proxy(
    {
      data: null,
      error,
    },
    {
      get(target, prop, receiver) {
        if (prop === 'then') {
          return (resolve: (value: unknown) => void) => resolve({ data: null, error });
        }

        if (prop === 'catch') {
          return (callback: (error: Error) => unknown) => Promise.resolve({ data: null, error }).catch(callback);
        }

        if (prop === 'finally') {
          return (callback: () => void) => Promise.resolve({ data: null, error }).finally(callback);
        }

        if (
          prop === 'select' ||
          prop === 'insert' ||
          prop === 'update' ||
          prop === 'delete' ||
          prop === 'upsert' ||
          prop === 'eq' ||
          prop === 'in' ||
          prop === 'order' ||
          prop === 'limit' ||
          prop === 'range' ||
          prop === 'match' ||
          prop === 'or' ||
          prop === 'filter' ||
          prop === 'not' ||
          prop === 'is' ||
          prop === 'contains' ||
          prop === 'over'
        ) {
          return () => builder;
        }

        if (prop === 'single' || prop === 'maybeSingle') {
          return () => Promise.resolve({ data: null, error });
        }

        if (prop === 'rpc') {
          return () => Promise.resolve({ data: null, error });
        }

        if (prop in target) {
          return Reflect.get(target, prop, receiver);
        }

        return undefined;
      },
    },
  );

  return builder as any;
}

function createFallbackSupabaseAdminClient() {
  const message = 'Supabase is not configured. Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY to enable server-side database access.';
  const error = new Error(message);

  return {
    auth: {
      getClaims: () => Promise.resolve({ data: { claims: null }, error }),
    },
    from: () => createFallbackQueryBuilder(message),
    storage: {
      from: () => ({
        upload: () => Promise.resolve({ data: null, error }),
        download: () => Promise.resolve({ data: null, error }),
        remove: () => Promise.resolve({ data: null, error }),
        getPublicUrl: () => ({ data: { publicUrl: '' }, error }),
      }),
    },
    removeChannel: () => undefined,
  } as any;
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    console.warn('[Supabase] Missing server credentials. Falling back to a local-safe client.');
    return createFallbackSupabaseAdminClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
